---
- name: install and start nginx 
  hosts: all
  become: true
  tasks: 
  - name: Install nginx
    apt: 
      name: nginx
      state: present
  - name: start nginx
    service: 
      name: nginx
      state: started
  - name: start enable
    service: 
      name: nginx
      state: enabled
  - name: Create index.html file
      file:
        path: /var/www/html/index.html
        state: touch
  - name: Add content to index.html
      lineinfile:
        path: /var/www/html/index.html
        line: "hello"
  - name: start enable
    service: 
      name: nginx
      state: restored